//
// Created by liam_ on 09/06/2023.
//

#ifndef FLIGHTSOFTWAREWORKSPACE_ADCSDRIVER_H
#define FLIGHTSOFTWAREWORKSPACE_ADCSDRIVER_H


// Start defining command and mode ID's specified in ADCS specification sheet
// Commands
typedef enum ADCSCommand {
    HT_PTL_RESET    = 0x01,
    HT_PTL_ACK      = 0x02,
    HT_PTL_FUN      = 0x03,
    HT_PTL_PING     = 0x04,
    HT_PTL_PULSE_CLOCK = 0x05,
    HT_PTL_WHO_AM_I = 0x10,
    HT_PLT_IDENTIFY = 0x11,
    HT_PTL_GET_SERIAL_NO = 0x12,
    HT_PTL_SET_BAUDRATE = 0x13,
    HT_PTL_GET_TIME = 0x14,
    HT_PTL_SET_TIME = 0x15,
    HT_GET_MODE = 0x16,
    HT_SET_MODE = 0x17,
    GET_SAFE_MODE_DATA_FRAME = 0x20,
    GET_NOMINAL_DATA_FRAME = 0x21,
    GET_HOUSEKEEPING_DATA_FRAME = 0x22,
    GET_ATTITUDE_ESTIMATE_FRAME = 0x23,
    GET_STATUS = 0x2F,
    GET_GYRO_READING = 0x30,
    GET_MTM_READING = 0x31,
    GET_SUNSENSOR_READING = 0x32,
    GET_STAR_LIST_DATA_FRAME = 0x33,
    GET_GNSS_READING = 0x34,
    SEND_CMD_FRAME = 0x40,
    SET_POWER_STATUS = 0x4d,
    SET_STAR_TRACKER_TEST_MODE = 0x4f,
    SET_SWITCHING_MODE_PARAMETERS = 0x50,
    SET_MEASUREMENT_MODE_PARAMETERS = 0x51,
    SET_MOMENTUM_DUMPING_MODE_PARAMETERS = 0x52,
    SET_DETUMBLING_MODE_PARAMETERS = 0x53,
    SET_CALIBRATION_MODE_PARAMETERS = 0x54,
    SET_SUN_NADIR_MODE_PARAMETERS = 0x55,
    SET_EARTH_TARGET_MODE_PARAMETERS = 0x56,
    SET_INERTIAL_TARGET_MODE_PARAMETERS = 0x57,
    UPDATE_CURRENT_SATELLITE_INERTIA = 0x60,
    UPLOAD_TLE = 0x61,
    UPLOAD_GNSS_POSITION = 0x62,
    SET_SATELLITE_PARAMETERS = 0x63,
    CHANGE_ACTUATOR_QUEUE_SIZE = 0x70,
    SET_ADCS_CONFIG_EXTERNAL = 0x71,
    GET_ADCS_CONFIG_EXTERNAL = 0x72,
    POWER_CYCLE = 0x7A,
    DEBUG = 0xFE
} ADCSCommand;

// Mode definitions
typedef enum ADCSMode {
    M_SLEEP             = 1,
    M_IDLE              = 2,
    M_SAFE              = 3,
    M_SWITCH            = 4,
    M_MEAS              = 5,
    M_DUMP              = 6,
    M_DETUMBLE          = 7,
    M_CALIBRATE         = 8,
    M_SUN_NADIR         = 9,
    M_EARTH_TRACK       = 10,
    M_INERTIAL          = 11
} ADCSMode;



class ADCSDriver {

};


#endif //FLIGHTSOFTWAREWORKSPACE_ADCSDRIVER_H
